### ISSUE TITLE
ModuleNotFoundError: No module named 'micropip'

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-lite#31]
https://lite.datasette.io/ is broken for me right now:

<img width="853" alt="image" src="https://user-images.githubusercontent.com/9599/174658896-10377274-fbe2-41ce-82fc-c3595f25f7bd.png">

```
Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 502, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 355, in run_async
    await coroutine
  File "<exec>", line 11, in <module>
ModuleNotFoundError: No module named 'micropip'
```

**Comment by simonw** [comment]
Only mention I can find of that error:

- https://github.com/pyodide/pyodide/issues/1899

**Comment by simonw** [comment]
https://pyodide.org/en/stable/usage/quickstart.html suggests:

`https://cdn.jsdelivr.net/pyodide/v0.20.0/full/pyodide.js`

**Comment by simonw** [comment]
This fixed it:
```diff
diff --git a/webworker.js b/webworker.js
index f14d4ea..9eaef41 100644
--- a/webworker.js
+++ b/webworker.js
@@ -1,4 +1,4 @@
-importScripts("https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.js");
+importScripts("https://cdn.jsdelivr.net/pyodide/v0.20.0/full/pyodide.js");
 
 function log(line) {
   console.log({line})
@@ -16,7 +16,7 @@ async function startDatasette(initialUrl) {
   }
   console.log({toLoad});
   self.pyodide = await loadPyodide({
-    indexURL: "https://cdn.jsdelivr.net/pyodide/dev/full/"
+    indexURL: "https://cdn.jsdelivr.net/pyodide/v0.20.0/full/"
   });
   await pyodide.loadPackage('micropip', log);
   await pyodide.loadPackage('ssl', log);
```

**Comment by simonw** [comment]
Confirmed, https://lite.datasette.io/ is fixed.
