### ISSUE TITLE
Datasette-Lite failing with multipart import error

### ISSUE THREAD

**Issue by wragge** [simonw/datasette-lite#79]
Datasette-Lite has started failing with the error:

```
Error

Traceback (most recent call last):
  File "/lib/python312.zip/_pyodide/_base.py", line 596, in eval_code_async
    await CodeRunner(
  File "/lib/python312.zip/_pyodide/_base.py", line 412, in run_async
    await coroutine
  File "<exec>", line 116, in <module>
  File "/lib/python3.12/site-packages/datasette/app.py", line 3, in <module>
    import asgi_csrf
  File "/lib/python3.12/site-packages/asgi_csrf.py", line 5, in <module>
    from multipart import FormParser
ModuleNotFoundError: No module named 'multipart'
```

It seems that the latest version of python-multipart has [renamed the import](https://github.com/Kludex/python-multipart/pull/166), so I'm wondering if that's the problem?

**Comment by wragge** [comment]
I've gotten my own Datasette-Lite repo to work for now by adding `await micropip.install("python-multipart==0.0.12")` into `webworker.js`. But I don't know why this works if the 0.0.13 version has been yanked.

**Comment by simonw** [comment]
OK, that fixed it - thanks everyone.
